
### Create Report
POST http://localhost:3000/reports
content-type: application/json

{ 
"price": 100000,
"make": "Datsun",
"model": "Shitter Thou",
"year": 2009,
"lng": 0,
"lat": 0,
"mileage": 100000
}

### Approve an existing report
PATCH http://localhost:3000/reports/6
content-type: application/json

{
    "approved": false
}

### Get a report