
### Find a user by id
GET http://localhost:3000/auth/5


### Create user
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "alex@monash.com",
    "password": "Perfection"
}

### Find user by email
GET http://localhost:3000/auth/?email=james@jameson.com

### Delete user with a given id
DELETE http://localhost:3000/auth/4

### Update a user
PATCH http://localhost:3000/auth/4
content-type: application/json

{
    "email": "james@jameson.com",
    "password": "sasdad"
}

### Signin
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "alex@monash.com",
    "password": "Perfection"
}